ifeq ($(OS), Windows_NT)
	PYTHON=python

else
	PYTHON=python3

endif


.PHONY: run_tarea run_ejercicio1 run_ejercicio2

run_tarea: run_ejercicio1 run_ejercicio2

run_ejercicio1:
	$(PYTHON) main.py

run_ejercicio2:
	$(PYTHON) ejercicio2.py
          
