PYTHON = python3

MAIN_SCRIPT = main.py
ALERGIA_SCRIPT = alergia.py
EVALUACION_SCRIPT = evaluacion.py
TIPOS_ALERGIAS_SCRIPT = tipos_alergias.py
EVALUACION_GENERAL_SCRIPT = evaluacion_general.py

ifeq ($(OS),Windows_NT)
    PYTHON = python
endif

run:
	$(PYTHON) $(MAIN_SCRIPT)

test:
	

clean:


.PHONY:
